import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
offset = { x = 0, y = 8}
size = 12


[env]
TERM = "xterm-256color"

[shell]
program = "tmux"

[window]
padding.x = 4
padding.y = 4
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]
